### ISSUE TITLE
Relative mean square error

### ISSUE THREAD

**Issue by joeylitalien** [tunabrain/tungsten#57] opened 2018-12-18 21:19 UTC
Hi Benedikt,

I was looking through the code for `hdrmanip` as it is a tool I often use in my research. I noticed something odd with the way you compute the relative MSE. [Line 147](https://github.com/tunabrain/tungsten/blob/74214128e08741af35615ac4832423d150ef88ca/src/hdrmanip/hdrmanip.cpp#L147) of the code reads:

```
rmse += sqr(imgA[i*3 + c] - imgB[i*3 + c])/(imgA[i*3 + c] + 1e-3f);
```

Shouldn't you square the denumerator too? At least that's what is proposed by [Rousselle et al. (2011)](https://www.cs.umd.edu/~zwicker/publications/AdaptiveSamplingGreedyError-SIGA11.pdf) if I'm not mistaken. Is there something I'm missing here? If this is indeed an error, did you use this code for Figure 5 of RJMLT, or was it fixed but never pushed?

Cheers,
Joey

**Comment by tunabrain** [comment] 2018-12-19 03:14
Good catch! That indeed looks like a bug, I pushed a fix. Thanks for pointing that out.

As far as the RJMLT paper goes, that should be fine - it uses MSE instead of relative MSE. The only one of my papers I can think of that used rMSE was the 2016 "Nonlinearly Weighted First-order Regression
for Denoising Monte Carlo Renderings" one, Figure 10; but there we used rMSE along with MSE, PSNR and SSIM, so the results should be fine.

**Closed by tunabrain** 2018-12-19 03:14 UTC
